#!/usr/bin/env php
<?php

declare(strict_types=1);

use NicolasBeauvais\Warden\Kernel;

define('WARDEN_START', microtime(true));

(static function () {
    $autoloadPaths = [
        __DIR__ . '/vendor/autoload.php',
        __DIR__ . '/../../autoload.php',
    ];

    foreach ($autoloadPaths as $autoloadPath) {
        if (!file_exists($autoloadPath)) {
            continue;
        }

        $validAutoloadPath = $autoloadPath;
    }

    if (!isset($validAutoloadPath)) {
        fwrite(
            STDERR,
            'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
            '    composer install' . PHP_EOL . PHP_EOL .
            'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
        );

        die(1);
    }

    require $validAutoloadPath;

    if (!Kernel::validPHPVersion()) {
        fwrite(
            STDERR,
            sprintf(
                'This version of Warden is only supported on PHP >= ' . Kernel::REQUIRED_PHP_VERSION .  PHP_EOL .
                'You are using PHP %s (%s).' . PHP_EOL,
                PHP_VERSION,
                PHP_BINARY
            )
        );

        die(1);
    }

    Kernel::bootstrap();
})();
