name: Code quality checks

on: [ push, pull_request ]

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse

  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2

        - name: PHPCS check
          uses: chekalsky/phpcs-action@v1
