name: PHPStan Check

on: [ push, pull_request ]

jobs:
  phpstan:
    name: PHPStan Check

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: PHPStan Check
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse
